apiVersion: v1
kind: PersistentVolume
metadata:
  name: exascale-web-pv
  namespace: keti-system
  labels:
    name: exascale-web
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.21.191
    path: /exascale-web