apiVersion: v1
kind: PersistentVolume
metadata:
  name: exascale-web-pv
  namespace: keti-system
  labels:
    name: exascale-web
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.5.20
    path: /exascale-web