kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: exascale-web-pvc
  namespace: keti-system
spec:
  volumeName: exascale-web-pv
  accessModes:
  - ReadWriteMany
  resources:
   requests:
    storage: 5Gi
  selector:
    matchLabels:
      name: exascale-web